//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_managers
    {
        public int m_id { get; set; }
        public string m_name { get; set; }
        public string m_password { get; set; }
        public int m_salary { get; set; }
        public string m_phone { get; set; }
        public Nullable<int> branch_id { get; set; }
    
        public virtual C_branch C_branch { get; set; }
    }
}
