//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_orders
    {
        public int o_id { get; set; }
        public System.DateTime o_date { get; set; }
        public string f_name { get; set; }
        public Nullable<int> c_id { get; set; }
    
        public virtual C_customers C_customers { get; set; }
        public virtual C_food C_food { get; set; }
    }
}
