//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_staff
    {
        public int s_id { get; set; }
        public string s_name { get; set; }
        public string s_password { get; set; }
        public int s_salary { get; set; }
        public int s_age { get; set; }
        public string s_phone { get; set; }
        public string s_specialty { get; set; }
        public Nullable<int> b_id { get; set; }
    
        public virtual C_branch C_branch { get; set; }
    }
}
