//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class resturantEntities : DbContext
    {
        public resturantEntities()
            : base("name=resturantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_branch> C_branch { get; set; }
        public virtual DbSet<C_customers> C_customers { get; set; }
        public virtual DbSet<C_food> C_food { get; set; }
        public virtual DbSet<C_managers> C_managers { get; set; }
        public virtual DbSet<C_orders> C_orders { get; set; }
        public virtual DbSet<C_staff> C_staff { get; set; }
    }
}
